blank_issues_enabled: false
contact_links:
    - name: Ask a question
      url: https://github.com/dnd-mapp/dma-ui-angular/discussions
      about: Ask and answer questions with the community.
    - name: Get general support
      url: https://github.com/dnd-mapp/dma-ui-angular/blob/main/SUPPORT.md
      about: Find resources for general support with the project.
